#!/usr/bin/env python3

import os
import sys
import json
import yaml
import click

from tabulate import tabulate
from termcolor import colored

# class to implement a custom YAML loader
class Loader(yaml.SafeLoader):
    def __init__(self, stream):
        self._root = os.path.split(stream.name)[0]
        self._state = []
        super(Loader, self).__init__(stream)

    def include(self, node):
        directory_path = self.construct_scalar(node)
        base_path = os.path.dirname(self.name)
        full_directory_path = os.path.join(base_path, directory_path)

        # 读取文件夹中所有的YAML文件
        data = {}
        for filename in os.listdir(full_directory_path):
            if filename.endswith('.yaml') or filename.endswith('.yml'):
                file_path = os.path.join(full_directory_path, filename)
                with open(file_path, 'r') as f:
                    # 合并yaml文件内容
                    file_data = yaml.load(f, Loader=yaml.FullLoader)
                    if isinstance(file_data, dict) and file_data:
                        data.update(file_data)
                        second_level = file_data[list(file_data.keys())[0]]
                        colored_data = self.check_fields(second_level)
                        self._state += [["State Name", colored(filename, 'blue')]]
                        self._state += colored_data
                    elif isinstance(file_data, list):
                        data[filename] = file_data
        return data

    def oneline(self, node):
        file_path = self.construct_scalar(node)
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File {file_path} not found")

        # 如果是 YAML 文件，合并内容
        with open(file_path, 'r') as f:
            return f.read()#.replace('\\n', '\n')

    def check_fields(self, yaml_data):
        fields = ['inputs', 'outputs', 'transitions', 'render', 'tasks']
        result = []
        for field in fields:
            if field in yaml_data:
                result.append([field, colored('Yes', 'green')])
            else:
                result.append([field, colored('No', 'red')])
        return result

    #@staticmethod
    def print_table(self, data):
        #headers = ['Field', 'Exists']
        headers = []
        print(tabulate(data, headers, tablefmt='grid'), file=sys.stderr)

    def __del__(self):
        if self._state:
            # transposed_data = list(zip(*self._state))
            # print(transposed_data)
            # self.print_table(transposed_data)
            self.print_table(self._state)

Loader.add_constructor('!include', Loader.include)
Loader.add_constructor('!oneline', Loader.oneline)

@click.group()
def cli():
    pass

@cli.command()
@click.argument('json_file', type=click.File('r'))
@click.option('--output', '-o', type=click.File('w'), default='-',
              help='Output file path. Defaults to stdout.')
def j2y(json_file, output):
    """Convert JSON to YAML."""
    json_data = json.load(json_file)
    yaml.dump(json_data, output, default_flow_style=False)


@cli.command()
@click.argument('yaml_file', type=click.File('r'))
@click.option('--output', '-o', type=click.File('w'), default='-',
              help='Output file path. Defaults to stdout.')
def y2j(yaml_file, output):
    """Convert YAML to JSON."""
    yaml_data = yaml.load(yaml_file, Loader)
    json.dump(yaml_data, output)


if __name__ == '__main__':
    cli()
