apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2023-07-25T09:51:39Z"
  generation: 41
  name: experimentllm
  namespace: kubeflow-user-example-com
  ownerReferences:
  - apiVersion: kubeflow.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Notebook
    name: experimentllm
    uid: e786049f-4e25-4500-b20a-e5f716e5cbae
  resourceVersion: "107465968"
  uid: c48a141e-a43b-4004-9bc3-cf39cdf779a7
spec:
  podManagementPolicy: OrderedReady
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      statefulset: experimentllm
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: experimentllm
        notebook-name: experimentllm
        statefulset: experimentllm
    spec:
      containers:
      - env:
        - name: NB_PREFIX
          value: /notebook/kubeflow-user-example-com/experimentllm
        image: mervynzhang/jupyter-cuda:11.8
        imagePullPolicy: IfNotPresent
        name: experimentllm
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        resources:
          limits:
            cpu: "48"
            memory: 120Gi
            nvidia.com/gpu: "4"
          requests:
            cpu: "40"
            memory: 100Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/jovyan
          name: experimentllm-volume
        workingDir: /home/jovyan
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 100
      serviceAccount: default-editor
      serviceAccountName: default-editor
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: experimentllm-volume
        persistentVolumeClaim:
          claimName: experimentllm-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 0
  collisionCount: 0
  currentRevision: experimentllm-75b964b874
  observedGeneration: 41
  replicas: 0
  updateRevision: experimentllm-75b964b874
